name: netology-aiohttp

services:

  db:
    image: postgres:17-alpine
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_NAME}

  app:
    build: .
    env_file:
      - .env
    environment:
      WAIT_HOSTS: ${POSTGRES_HOST}:${POSTGRES_PORT}
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - db

  tests:
    build:
      context: .
      dockerfile: tests.Dockerfile
    env_file:
      - .env
    environment:
      WAIT_HOSTS: ${POSTGRES_HOST}:${POSTGRES_PORT}, app:8080
    depends_on:
      - db
      - app
