from environs import env

POSTGRES_NAME = env('POSTGRES_NAME')
POSTGRES_USER = env('POSTGRES_USER')
POSTGRES_PASS = env('POSTGRES_PASS')
POSTGRES_HOST = env('POSTGRES_HOST')
POSTGRES_PORT = env('POSTGRES_PORT')

DB_URL = (
    f'postgresql+psycopg://{POSTGRES_USER}:{POSTGRES_PASS}@'
    f'{POSTGRES_HOST}:{POSTGRES_PORT}/'
    f'{POSTGRES_NAME}'
)

APP_URL = env('APP_URL')
